CREATE TABLE "BLUE1"."가구" 
   (	"번호" NUMBER, 
	"이름" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"제작사" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"가격" NUMBER NOT NULL ENABLE, 
	"상세정보" VARCHAR2(200 BYTE), 
	 PRIMARY KEY ("번호"));
	 
	  CREATE TABLE "BLUE1"."회원" 
   (	"아이디" VARCHAR2(30 BYTE), 
	"비밀번호" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"주소" VARCHAR2(30 BYTE), 
	"전화번호" VARCHAR2(30 BYTE), 
	 PRIMARY KEY ("아이디"));